services:
  # Backend API
  - type: web
    name: pos-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/tables

  # Frontend
  - type: web
    name: pos-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile.frontend
    dockerContext: ./
    plan: free
    buildCommand: |
      docker build \
        --build-arg VITE_API_URL=$VITE_API_URL \
        -f Dockerfile.frontend \
        -t pos-frontend .
    envVars:
      - key: VITE_API_URL
        sync: false
